[project]
name = "telegram-bot"
version = "0.1.0"
description = "Telegram notification service"
requires-python = ">=3.13"

dependencies = []

[project.optional-dependencies]
server = [
    "fastapi",
    "httpx",
    "python-dotenv",
    "uvicorn"
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk",
]

[tool.setuptools]
py-modules = [
    "main",
    "worker",
]

[tool.setuptools.packages.find]
include = ["app*"]