main = "src/index.js"
compatibility_date = "2026-08-25"

[vars]
PRIMARY_BACKEND_URL = "https://telegram-api-1.shiday.my.id"
SECONDARY_BACKEND_URL = "https://telegram-api-2.shiday.my.i"
TELEGRAM_WEBHOOK_PATH = "/webhook"
REQUEST_TIMEOUT_MS = "7000"

[observability]
enabled = true